### ISSUE TITLE
typo in inqcolorfromrgb

### ISSUE THREAD

**Issue by tv11** [sciapp/python-gr#1]
the python bindings currently pass 
red green green 
instead of 
red green blue 
to the library function.
A patch to fix this is attached.
[patch_inqcolorfromrgb_python_gr.txt](https://github.com/sciapp/python-gr/files/1660670/patch_inqcolorfromrgb_python_gr.txt)

**Comment by FlorianRhiem** [comment]
Thank you for reporting this bug. It was fixed in 55fc78908282b8ca81accd0ab5d72f21829fe02c and we will release a new version today.
