### ISSUE TITLE
How would one use gr.fillarea on a GRWidget?

### ISSUE THREAD

**Issue by EmDash00** [sciapp/python-gr#10]
Basically the question above. There's not an exposed method in qtgr and I'm rather confused about the whole concept of gr workstations and how one might use them for multiple qt windows.

**Comment by FlorianRhiem** [comment]
See the [pygrwidget example](https://github.com/sciapp/python-gr/blob/18ade65b514110fcc8db548e772f5bf76e26e835/examples/pygrwidgetqt5_ex.py#L57) for an example of how to use normal `gr` functions with a `GRWidget`. The example uses `gr.surface`, `gr.contour` and `gr.axes`, but you can replace those with calls to other `gr` functions like `gr.fillarea`.

For multiple qt windows you probably want to use multiple `GRWidget` objects.

You can find some more information on workstations in the [documentation](https://gr-framework.org/workstations.html).
