### ISSUE TITLE
qt5plugin doesn't exist 

### ISSUE THREAD

**Issue by spewil** [sciapp/python-gr#18]
hi, 

i'm sure this is something silly, but i'm getting this error in the examples:

`GKS: dlopen(/Users/spencerw/miniconda3/envs/motor/lib/python3.7/site-packages/gr/lib/qt5plugin.so, 1): Library not loaded: @rpath/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Users/spencerw/miniconda3/envs/motor/lib/python3.7/site-packages/gr/lib/qt5plugin.so
  Reason: image not found
`

i'm running python 3.7.3 in a conda environment. in the `lib` folder I see `qtplugin.so` but not `qt5plugin.so` ...  

I'd like to try GR as I've been using PyQtGraph and I'm looking for better performance with live plotting of data coming in at 2kHZ on 64 channels. 

thanks!

**Comment by FlorianRhiem** [comment]
> i'm running python 3.7.3 in a conda environment. in the lib folder I see qtplugin.so but not qt5plugin.so ...

Are you certain? The error message indicates that `/Users/spencerw/miniconda3/envs/motor/lib/python3.7/site-packages/gr/lib/qt5plugin.so` exists, but cannot be loaded as the QtWidgets library cannot be loaded.

Do you have Qt5 installed? If so, where?

**Comment by Tillsten** [comment]
Maybe it is related: under windows I get `GKS: Qt5 support not compiled in` when using a pip installed gr

**Comment by EmDash00** [comment]
I'm getting the same issue.

**Comment by birkenfeld** [comment]
@Tillsten on Windows, you can now select the MSVC build of gr by setting `GR_BUILD_VARIANT=msvc` during `setup.py install` - this one has a Qt5 plugin compiled in and works with PyQt5.

**Comment by IngoMeyer441** [comment]
Since version [v1.24.0](https://pypi.org/project/gr/1.24.0/) the MSVC build is used by default. So GR works with PyQt / PySide without setting any environment variables.
