### ISSUE TITLE
Qt5 QWheelEvent does not have a member delta

### ISSUE THREAD

**Issue by jkrueger1** [sciapp/python-gr#2]
Using Qt5 the use of the mouse wheel creates an error:

 'QWheelEvent' object has no attribute 'delta'

The corresponding member is angleDelta in Qt5

**Comment by FlorianRhiem** [comment]
Hello Jens,
thank you for reporting this issue! I have fixed this in the develop branch (5d17bacfc2d99c843c21b9ed51da3c7ff22691e6) and we will release a new version soon.

**Comment by FlorianRhiem** [comment]
gr 1.2.0 is up on [PyPI](https://pypi.python.org/pypi/gr/1.2.0) and should solve this issue. Please update and if the issue persists, let us know.

**Comment by jkrueger1** [comment]
It works. The switch to 1.2.0 fixes another issues too. Thanks.
