### ISSUE TITLE
spectrum3 example with Py3.8

### ISSUE THREAD

**Issue by rjsdotorg** [sciapp/python-gr#21]
https://gr-framework.org/examples/spectrum3
[spectrum3.zip](https://github.com/sciapp/python-gr/files/4554678/spectrum3.zip)
.html
returns
C:\Python38\Tools\scripts\GR\gr2.py:17: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves s
urprisingly on unicode inputs. Use frombuffer instead
  amplitudes = np.fromstring(mic.read(SAMPLES), dtype=np.short)
Traceback (most recent call last):
  File "C:\Python38\Tools\scripts\GR\gr2.py", line 29, in <module>
    power = get_spectrum()
  File "C:\Python38\Tools\scripts\GR\gr2.py", line 18, in get_spectrum
    return abs(np.fft.fft(amplitudes / 32768.0))[:SAMPLES/2]
TypeError: slice indices must be integers or None or have an __index__ method

Using Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
 numpy. __version__ = '1.18.1'

after fixing lines 17 & 18
    amplitudes = np.frombuffer(mic.read(SAMPLES), dtype=np.short)
    return abs(np.fft.fft(amplitudes / 32768.0))[:int(SAMPLES/2)]

there are no errors, but no gl window. print() does show data in.

**Comment by rjsdotorg** [comment]
Other examples such as https://gr-framework.org/examples/audio_ex.html also have Py3.8 or numpy >1.18 issues, and do not show windows once syntax errors are fixed.

**Comment by jheinen** [comment]
Thanks for the hint. We'll fix this tomorrow ...

**Comment by FlorianRhiem** [comment]
The examples should be working with Python 3 now as part of release 1.15.0.
