### ISSUE TITLE
GR_BUILD_VARIANT=mvsc Errors 

### ISSUE THREAD

**Issue by EmDash00** [sciapp/python-gr#25]
When installing with pip, you get the following error:

```
urlopen error Failed to download file from: https://github.com/sciapp/gr/releases/download/v0.55.0/gr-0.55.0-Windows-x86_64-mvsc.tar.gz, http://gr-framework.org/downloads/gr-0.55.0-Windows-x86_64-mvsc.tar.gz```

**Comment by FlorianRhiem** [comment]
Hey @EmDash00,

you probably meant to use `GR_BUILD_VARIANT=msvc`, right?

**Comment by EmDash00** [comment]
Ah yes, that would do it! Fixed.

**Comment by IngoMeyer441** [comment]
Since version [v1.24.0](https://pypi.org/project/gr/1.24.0/) the MSVC build is used by default.
