### ISSUE TITLE
axeslbl failure 

### ISSUE THREAD

**Issue by michele-brambilla** [sciapp/python-gr#27]
After upgrading the OS to MacOS 10.15 (catalina) apps using qtgr crash. I could track the problem down to the call to `_axeslbl_callback` from `gr/__init.py__::axeslbl`.

python 3.8.12
Qt 5.15.2
PyQt 5.15.2
python-gr is the latest form master

**Comment by FlorianRhiem** [comment]
Hey @michele-brambilla,

what version of the GR runtime are you using? You can check by importing gr and running `gr.version()`, and you can download the latest for macOS from https://gr-framework.org/downloads/gr-latest-Darwin-x86_64.tar.gz.

**Comment by cfelder** [comment]
Thanks for reaching out @michele-brambilla.

if this is still an issue may I ask you to provide a stack trace.

Have a nice weekend.
