### ISSUE TITLE
Improve python wheel build

### ISSUE THREAD

**Issue by bpedersen2** [sciapp/python-gr#28]
The wheel does include platform-specific files, but is not marked as such ( gr-...-any.whl).

See https://stackoverflow.com/questions/45150304/how-to-force-a-python-wheel-to-be-platform-specific-when-building-it how make setup.py aware of this to get platfrm-specific wheels.

**Comment by FlorianRhiem** [comment]
Hello @bpedersen2,

I am somewhat confused, as I am not aware of us distributing wheels for GR. What wheels are you referring to?

**Comment by bpedersen2** [comment]
It  is correct that currently no wheels are provided by the gr project, but this also affects building those wheels locally ( we use virtualenvs with gr heavily in our CI jobs and have a local mirror of pre-built wheels to speed up setup of those venvs)

**Comment by bpedersen2** [comment]
I'll upload a pull  request soon.

**Comment by FlorianRhiem** [comment]
Ah, okay. Currently, while installing GR, the required platform-specific files are downloaded either from github or from gr-framework.org if it's not a stable version or github is unavailable. There are files for:
- Debian (x86_64 and armhf)
- Ubuntu (x86_64)
- Arch Linux (x86_64)
- CentOS 6 (x86_64 and i386)
- CentOS 7 (x86_64)
- FreeBSD (x86_64)
- macOS (x86_64)
- Windows (MSVC)
- Windows (MinGW, x86_64 and i686)

and these platforms don't cleanly map to the platform names used by wheels, as far as I'm aware. This is part of the reason why we do not provide wheels but instead download the binaries based on the specific system.
