### ISSUE TITLE
animation not loaded to jupyter notebook

### ISSUE THREAD

**Issue by eunjongkim** [sciapp/python-gr#3]
I have noticed that `gr.inline('mov')` fails to load the animation to jupyter notebook (ffmpeg is installed in my computer).

For instance, running the following code give "invalid source" displayed at the output of the cell
```
import math
import gr

import gr3

# plot gr output inline
gr.inline('mov')

gr.setviewport(0, 1, 0, 1)
gr3.setbackgroundcolor(1, 1, 1, 1)

for t in range(200):
    f = 0.0375 * (math.cos(t*0.2) * 0.995**t + 1.3)
    n = 90
    points = [(math.sin(i*math.pi/8), n*0.035-i*f, math.cos(i*math.pi/8)) for i in range(n-5)]
    points.append((0, points[-1][1], 0))
    points.append((0, points[-1][1]-0.5, 0))
    points.append((0, points[-1][1]-1, 0))
    points.insert(0, (0, points[0][1], 0))
    points.insert(0, (0, points[0][1]+2, 0))
    colors = [(1, 1, 1)]*n
    radii = [0.1]*n
    gr3.clear()
    gr3.drawtubemesh(n, points, colors, radii)
    gr3.drawspheremesh(1, points[-1], colors, 0.75)
    gr.clearws()
    gr3.drawimage(0, 1, 0, 1, 500, 500, gr3.GR3_Drawable.GR3_DRAWABLE_GKS)
    gr.updatews()
gr.show()
```

I was able to fix this by following:
in line 2323 of `python-gr/gr/__init__.py`
```
content = HTML(data='<video controls autoplay type="video/mp4" src="data:video/mp4;base64,{0}">'.format(b64encode(open('gks.mov', 'rb').read()).decode('ascii')))
```
This seems to have arised from change in IPython.display.HTML

Best,
Eunjong

**Comment by FlorianRhiem** [comment]
Thank you for reporting this issue. As `b64encode` returns binary data, decoding it before passing it to `format` makes sense. I have [committed this change](https://github.com/sciapp/python-gr/commit/46c0c29c6834cb3557131b913d91658ad5312719) into our [develop](https://github.com/sciapp/python-gr/tree/develop)ment branch and it will be part of the next release.
