### ISSUE TITLE
Plotting from the terminal

### ISSUE THREAD

**Issue by pauljurczak** [sciapp/python-gr#30]
This is a repost of https://stackoverflow.com/questions/70563646/gr-examples-in-python-dont-open-a-window-with-visualization.

I installed GR and its dependencies on Ubuntu 20.04 with Python 3.8.10 following instructions on https://gr-framework.org/python.html#installation. The first example:
```
from gr.pygr import mlab
mlab.plot(range(100), lambda x: x**2)
```
creates a plot in Jupyter as expected. What is a way to get a plot when run from the terminal?

**Comment by FlorianRhiem** [comment]
Hey Paul,
normally, running that command should open a GKS Qt window and display the plot in there. Are there any error messages in the terminal after running the `mlab.plot` command?

If not, what you can try is to start GKS Qt manually in the hope that you'll get any potential error messages that way, e.g. if there is a missing dependency. To do so, try running `./bin/gksqt` from within the GR package directory.

Also, please print the GR version, just in case you might have an older version of GR:
```python
import gr
print(gr.version())
```

**Comment by pauljurczak** [comment]
Nothing gets printed to the terminal.

The version is `Runtime: 0.58.0 / Python: 1.18.0`

Here is the error I'm getting when running `gksqt`:
```
paul@desktop:~/st/vis/.vis/lib/python3.8/site-packages/gr/bin$ ./gksqt
GKS: file open error (/usr/local/gr/fonts/gksfont.dat)
open: No such file or directory
```
It looks like I'm missing a dependency, but I did:
```
apt install libxt6 libxrender1 libxext6 libgl1-mesa-glx libqt5widgets5
```

**Comment by FlorianRhiem** [comment]
That actually looks like it should work. Try starting `gksqt` after setting the `GRDIR` environment variable to the gr directory, e.g. by running `GRDIR=/home/paul/st/vis/.vis/lib/python3.8/site-packages/gr/ ./gksqt`, that way `gksfont.dat` should be found. If a dependency like Qt5 was missing (or unable to be found) that would've been reported earlier.

If gksqt starts, doesn't print any errors and just seems to be doing nothing, that's the correct behavior as it waits for connections from the GR libraries sending it commands (e.g. to open a window). You can then try to run something like

```
import gr
gr.polyline([0, 1], [0, 1])
gr.updatews()
```

to see if that does anything.

**Comment by pauljurczak** [comment]
`./gksqt` launches without an error, but exits without printing any message as soon as I run the script you provided.

**Comment by cfelder** [comment]
Either use an interactive environment, e.g. ``ipython`` or ``python -i`` or add ``input()`` to the end of your script.

**Comment by pauljurczak** [comment]
Thank you. `input()` solves the problem.
