### ISSUE TITLE
Wrapping GR FigureCanvas in Qt Widget

### ISSUE THREAD

**Issue by mfreer** [sciapp/python-gr#4]
Following my initial inquiry at https://github.com/sciapp/gr/issues/30#issuecomment-495079634, I am looking for a way to wrap a GR `FigureCanvas` object in a way that can be added to an existing PyQt layout. Below is a very simplified code of the way I'm currently doing things with the Qt5Agg `FigureCanvas`:

```python
import sys
from PyQt5 import QtCore, QtWidgets

import numpy
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure


class ApplicationWindow(QtWidgets.QMainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self.setAttribute(QtCore.Qt.WA_DeleteOnClose)
        self.setWindowTitle("QT5 matplotlib example")

        self.main_widget = QtWidgets.QWidget(self)

        fig = Figure(tight_layout=True)

        fig_canvas = FigureCanvas(fig)

        v_layout = QtWidgets.QVBoxLayout(self.main_widget)
        v_layout.addWidget(fig_canvas)

        x = numpy.arange(0, 2 * numpy.pi, numpy.pi / 100)
        y = numpy.sin(x)

        ax = fig.add_subplot(111)

        ax.plot(x, y)

        self.main_widget.setFocus()
        self.setCentralWidget(self.main_widget)


qApp = QtWidgets.QApplication(sys.argv)

app = ApplicationWindow()
app.show()
sys.exit(qApp.exec_())
```

Currently, my attempts to integrate the `FigureCanvas` from the GR matplotlib backend raises an error as Qt doesn't recognize the `FigureCanvasGR` type. Perhaps I am missing an existing capability, but essentially I am looking for a way (using QtGR or other) to wrap the GR `FigureCanvas` in an object that Qt will understand.

**Comment by FlorianRhiem** [comment]
Thank you for the example. I've added a `FigureCanvasQtGR` class to it which combines the `GRWidget` with the `FigureCanvasGR` from the GR matplotlib backend. Please give it a try:
```python
import sys
from PyQt5 import QtCore, QtWidgets

import numpy
from matplotlib.figure import Figure

from qtgr import GRWidget
from qtgr.backend import QtCore
from gr.matplotlib.backend_gr import FigureCanvasGR


class FigureCanvasQtGR(GRWidget, FigureCanvasGR):
    def __init__(self, figure, parent=None):
        super(FigureCanvasQtGR, self).__init__(parent, figure=figure)

    def sizeHint(self):
        width, height = self.get_width_height()
        return QtCore.QSize(width, height)

    def resizeEvent(self, event):
        super(FigureCanvasQtGR, self).resizeEvent(event)
        self.figure.set_size_inches(self._mwidth / 0.0254, self._mheight / 0.0254, forward=False)
        self.renderer.width, self.renderer.height = self.get_width_height()
        self.renderer.configure()
        # This font size fix can be moved into RendererGR
        if not hasattr(self.renderer, 'original_nominal_fontsize'):
            self.renderer.original_nominal_fontsize = self.renderer.nominal_fontsize
        self.renderer.nominal_fontsize = self.renderer.original_nominal_fontsize * min(640.0 / self.renderer.width, 480.0 / self.renderer.height)

    def draw(self):
        FigureCanvasGR.draw(self)


class ApplicationWindow(QtWidgets.QMainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self.setAttribute(QtCore.Qt.WA_DeleteOnClose)
        self.setWindowTitle("QT5 matplotlib example")

        self.main_widget = QtWidgets.QWidget(self)

        fig = Figure(tight_layout=True)

        fig_canvas = FigureCanvasQtGR(fig)

        v_layout = QtWidgets.QVBoxLayout(self.main_widget)
        v_layout.addWidget(fig_canvas)

        x = numpy.arange(0, 2 * numpy.pi, numpy.pi / 100)
        y = numpy.sin(x)

        ax = fig.add_subplot(111)

        ax.plot(x, y)

        self.main_widget.setFocus()
        self.setCentralWidget(self.main_widget)


qApp = QtWidgets.QApplication(sys.argv)

app = ApplicationWindow()
app.show()
sys.exit(qApp.exec_())
```

**Comment by mfreer** [comment]
Thanks for that - looks straightforward enough to implement. I gave it a try, and it is raising an error in the renderer: 

```
Traceback (most recent call last):
  File "matplotlib_example.py", line 31, in resizeEvent
    self.renderer.configure()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gr/matplotlib/backend_gr.py", line 54, in configure
    mwidth *= self.width / width
ZeroDivisionError: division by zero 
```
Do I need to set some window bounds somewhere to make sure width is getting set to a non-zero value before `self.renderer.configure()` is called?

**Comment by FlorianRhiem** [comment]
Odd, that `width` is the width as returned by `gr.inqdspsize()` and should not be zero. If you run the example exactly how I posted it, does that work for you? If so, can you send me the example you're using now?

**Comment by mfreer** [comment]
Strange... I'm using the example exactly how it was posted, and getting that error.

**Comment by FlorianRhiem** [comment]
Hm, the line number in the traceback doesn't fit, so I thought you might've adopted the class into a different Qt application / demo. What operating system and what version of Qt are you using? I'll try to replicate the issue when I'm back in the office.

**Comment by mfreer** [comment]
Ah sorry, that traceback was from an earlier test I was doing this morning adding some print lines and size definitions to see what might be going wrong. Here is the traceback from the example you provided:

```
Traceback (most recent call last):
  File "gr_test.py", line 24, in resizeEvent
    self.renderer.configure()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gr/matplotlib/backend_gr.py", line 54, in configure
    mwidth *= self.width / width
ZeroDivisionError: division by zero
Abort
Exit 134
```
In any case, I'm on MacOSX 10.14 using Qt5 (5.12.2).

**Comment by FlorianRhiem** [comment]
I'm using macOS 10.14.5 with Qt 5.12.2 as well, but I can't reproduce the issue. Still, I can see why the code might cause issues for workstation types with changing sizes and resolutions. I'm attaching an archive with a `backend_gr.py` which you can use to replace your current `gr/matplotlib/backend_gr.py` and an updated example. In this code, the `RendererGR` class only relies on `gr.inqdspsize()` if no `workstation_dpi` attribute is set and the example contains a `FigureCanvasQtGR` which sets it.

Please let me know whether this works on your system.

[Archive.zip](https://github.com/sciapp/python-gr/files/3222542/Archive.zip)

**Comment by mfreer** [comment]
Thanks for the new files. I have tested these, and I am now able to launch the code without any Python errors, but the FigureCanvas is showing up blank. On launch, I'm getting the message that "GKS: Qt5 support not compiled in" so I'm wondering if this could also be the cause of the earlier errors I was getting. 

I installed python-gr using pip, and everything seemed to go smoothly, but I'm wondering if it wasn't able to properly build GR with Qt5 support if it couldn't find my qmake installation. I tried building GR from source, and noticed it didn't immediately find Qt5 without some guidance, so perhaps this is a cause? I'm currently still attempting to build from source, but have run into other non-Qt5 related problems (some problem with zmq.h).

Otherwise, is there perhaps a particular environment variable set on your system that might be missing on mine?

**Comment by mfreer** [comment]
I spent a bit more time on this, and was able to build and install GR from source (ensuring it was able to use my Qt5 installation), as well as remove the PIP installation of Python-GR and reinstall that from source files as well. However I still got the same behavior when trying to launch test.py (message that "GKS: Qt5 support not compiled in" and blank `FigureCanvas`). 

I did some more digging, and I found that I get the "GKS: Qt5 support not compiled in" message whenever GKS_WSTYPE is set to 381. However, I don't get this message if I set GKS_WSTYPE to 411 (e.g. in another script I was testing, or in the QtGR __init__.py). So in the latter case, running test.py no longer produces the "GKS: Qt5 support not compiled in" message, but the window stays blank, with the plot showing up in a separate GKS QtTerm window (see screenshot). 

<img width="1173" alt="Screen Shot 2019-05-28 at 15 49 27" src="https://user-images.githubusercontent.com/1375409/58514855-479fa880-8160-11e9-9bb5-d7bca9ae4662.png">

Do I understand correctly that gksqt also relies on the qt5plugin?

**Comment by FlorianRhiem** [comment]
Yes, the message "GKS: Qt5 support not compiled in" explains why the division by zero happened. The dimensions reported by `inqdspsize` are queried from the qt5plugin. `gksqt` can use either Qt4 or Qt5, which depends on the build environment, as some of the systems gks should run on still use Qt4.

I'm not sure why neither Qt5 nor Qt4 support is included into the binaries we currently provide on macOS, it might be a build system issue that also causes your build to lack a working qt5plugin. I'll check and let you know!

**Comment by FlorianRhiem** [comment]
> I spent a bit more time on this, and was able to build and install GR from source (ensuring it was able to use my Qt5 installation)

Could you upload the log of your build? If Qt5 was found, the compilation of the qt5plugin should *not* have `-DNO_QT5` set.

**Comment by FlorianRhiem** [comment]
We have just released GR runtime version 0.40.0 and python gr package version 1.10.0. The v0.40.0 binaries include Qt5 support for macOS again, so please try using these. If you pip install gr, you should get them automatically.

**Comment by mfreer** [comment]
> > I spent a bit more time on this, and was able to build and install GR from source (ensuring it was able to use my Qt5 installation)
> 
> Could you upload the log of your build? If Qt5 was found, the compilation of the qt5plugin should _not_ have `-DNO_QT5` set.

Sure, log of my build is attached. 
[log.txt](https://github.com/sciapp/python-gr/files/3233547/log.txt)

**Comment by mfreer** [comment]
I tried using the newest version from pip, and I was at first getting a different error:

```
GKS: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gr/lib/qt5plugin.so, 1): Library not loaded: @rpath/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gr/lib/qt5plugin.so
  Reason: image not found
```

I'm not sure why it is not loading QtWidgets. The referenced file exists in the location where @rpath is searching for it (/opt/local/libexec/qt5/lib). I noticed the files installed at this location had a slightly different version (5.12.3) than those installed in my Qt working directory (5.12.2), so I overwrote these with the Qt working directory files. It seems the newer files were from the Macports Qt install. With these files replaced, I am now able to run the test.py file successfully! Thank you very much for your help on this - it is very much appreciated. Now to attempt to integrate this into my other project, and see if it can also work on Windows 10.

**Comment by FlorianRhiem** [comment]
Thanks, the log shows that the qt5plugin is built properly. Perhaps the gr module was looking for the libraries in the wrong place? In any case I'm glad that it works with the new release!

This should work on Windows 10, though I haven't tested it there yet. Let me know if you run into further issues and if the `FigureCanvasQtGR` works for your requirements. We can add it to the package then.

**Comment by mfreer** [comment]
Yeah I'm not sure why things didn't work when I built it myself. Are there any other flags that might need to be set to ensure GKS knows it should be built with Qt5 support?

In any case, I've been working on integrating the GR + Qt `FigureCanvas` in my application. It works, in principle, but it seems to struggle with what I'm trying to use it for, but perhaps I'm not implementing it correctly. Essentially, the `FigureCanvas` in my application should display 2 subplots - one with a time series, the other with a `pcolormesh` object which shows a binned histogram over time (y axis is bins, x axis is time, z axis is a calculated value at those points). It is this `pcolormesh` that drove me to seek out GR, since with larger datasets (greater than 20k points on the time axis), the `draw_quad_mesh` method of the default `RendererAgg` gets bogged down (several seconds per call).

As a test, I modified the test.py file you created with something that more closely resembles my use case. I also added a line to switch between `FigureCanvasQtGr` and `FigureCanvasQTAgg` for comparison. When running the script with `FigureCanvasQtGr`, it seems to get 'stuck' on the `pcolormesh` generation. Is there perhaps a better way to make this plot than the way I'm currently doing it? The test file I'm working with is attached.

[test.py.zip](https://github.com/sciapp/python-gr/files/3234063/test.py.zip)

**Comment by FlorianRhiem** [comment]
> Yeah I'm not sure why things didn't work when I built it myself. Are there any other flags that might need to be set to ensure GKS knows it should be built with Qt5 support?

There is a script which detects thirdparty dependencies like Qt5 and either sets the required compilation flags or sets something like `-DNO_QT5`. The qt5plugin (in `qtplugin_impl.cxx`) basically checks for that macro definition and either uses Qt5 or prints that Qt5 support is not compiled in. It is slightly more complicated than that (using another NO_QT macro which gets defined if NO_QT5 is defined so that the same implementation code for Qt4 and Qt5 can be used, but your log shows that the qt5plugin gets the right flags. I suspect that the python code might have used a different gr installation than the one you built.

> In any case, I've been working on integrating the GR + Qt `FigureCanvas` in my application. It works, in principle, but it seems to struggle with what I'm trying to use it for, but perhaps I'm not implementing it correctly. Essentially, the `FigureCanvas` in my application should display 2 subplots - one with a time series, the other with a `pcolormesh` object which shows a binned histogram over time (y axis is bins, x axis is time, z axis is a calculated value at those points). It is this `pcolormesh` that drove me to seek out GR, since with larger datasets (greater than 20k points on the time axis), the `draw_quad_mesh` method of the default `RendererAgg` gets bogged down (several seconds per call).
> 
> As a test, I modified the test.py file you created with something that more closely resembles my use case. I also added a line to switch between `FigureCanvasQtGr` and `FigureCanvasQTAgg` for comparison. When running the script with `FigureCanvasQtGr`, it seems to get 'stuck' on the `pcolormesh` generation. Is there perhaps a better way to make this plot than the way I'm currently doing it? The test file I'm working with is attached.
> 
> [test.py.zip](https://github.com/sciapp/python-gr/files/3234063/test.py.zip)
 
I'll have to look into what's causing this.

In any case it sounds like a better approach would be to also perform binning along the time axis to a number of points appropriate to the desired resolution. Otherwise you might 'lose' information to the resampling which has to happen when drawing an (at least) 20k pixels wide image to the widget area. Or perhaps I'm missing something here?

**Comment by FlorianRhiem** [comment]
The issue with the `pcolormesh` call is that it is broken down into individual paths consisting of five points, which a lot of overhead for each small quad. This happens because the GR renderer class does not implement the optional `draw_quad_mesh` method, which leads to the quad mesh being handled as a path collection and finally as individual paths.

Even the `draw_quad_mesh` method seems far too generic for your use case, as it even supports non-convex polygons in the mesh, while `pcolormesh` should produce a far more simple mesh. From what you've written I would guess that the non-uniform steps in x and y are the important requirements, without any need for more complex geometry?

**Comment by mfreer** [comment]
> In any case it sounds like a better approach would be to also perform binning along the time axis to a number of points appropriate to the desired resolution. Otherwise you might 'lose' information to the resampling which has to happen when drawing an (at least) 20k pixels wide image to the widget area. Or perhaps I'm missing something here?

This is a good suggestion - I've considered it, since above a certain point, the data will be resampled anyway. There are some complexities on how the data needs to be 'binned' along the time axis, but if I can put together a rapid method to do this calculation, it might also help speed things up from the plotting perspective

> Even the draw_quad_mesh method seems far too generic for your use case, as it even supports non-convex polygons in the mesh, while pcolormesh should produce a far more simple mesh. From what you've written I would guess that the non-uniform steps in x and y are the important requirements, without any need for more complex geometry?

Yes, the biggest limitation on this plot is the non-uniform steps in x and y. The x-axis, being time, is usually linear, but has the potential for gaps in the data. The y-axis is nonlinear, so this limits options for plotting. I made some attempts to use MatPlotLib's `imshow` and `NonUniformImage` functions to improve plotting speed, but in the end, these didn't have the flexibility to handle the axes spacings of my data.

**Comment by FlorianRhiem** [comment]
> There are some complexities on how the data needs to be 'binned' along the time axis, but if I can put together a rapid method to do this calculation, it might also help speed things up from the plotting perspective

Then I'd recommend doing this before passing the data to the plotting library, as it's unlikely that matplotlib or gr will handle these complexities correctly by default for your data. For example, GR currently uses nearest neighbor for resampling images. Someone is working on adding Lanczos resampling and similar methods, but that also might not be what you need here. GR does not have any support for non-uniform steps for image data at this time, but that might be something we could add in the future, on top of the improved resampling.

**Comment by FlorianRhiem** [comment]
Have you been able to solve your problems with the interpolation/resampling?

**Comment by mfreer** [comment]
Thanks for checking in. I followed your advice and did some resampling prior to passing to the plotting library. Things are much smoother now given the reduced size of the array that is being plotted.
