### ISSUE TITLE
Plotting performance is slow compared to results advertised on gr-framework.org

### ISSUE THREAD

**Issue by ghost** [sciapp/python-gr#6]
Running on macOS Mojave 10.14.5, I'm running the anim example provided [here on gr-framework.org](https://gr-framework.org/examples/anim.html).

According that page, the expected results are:
```
fps (mpl):   29
fps  (GR): 1002
  speedup:   34.6
```

However, I'm observing (in Python 2.7.10, using GR module 1.10.0):
```
fps (mpl):   34
fps  (GR):  118
  speedup:    3.5
```

In contrast, when running the [the figure output performance example figanim](https://gr-framework.org/examples/figanim.html) on my machine, it shows something on the order of the expected speedup:
```
.................................................fps (mpl):   12
.................................................fps  (GR): 1865
  speedup:  155.4
```

I apologize if the information here is lacking. I'm not sure what the next steps would be to diagnose or continue profiling.

**Comment by jheinen** [comment]
If you set the `GKSwstype` environment to `gksqt`, you should get a much higher speedup. This is because the line drawing functions in the default GKSTerm have lost performance in the last macOS versions.

@FlorianRhiem : We should probably add this setting to the `anim.py` script (as we did already in `anim.jl`).

**Comment by ghost** [comment]
Unfortunately, I'm seeing only ~60% better performance with gksqt, and qualitatively the plot animation is *much* less smooth than when using GKSTerm:
```
GKSwstype="gksqt" python testme.py 
fps (mpl):   29
fps  (GR):  132
  speedup:    4.6
```
```
python testme.py 
fps (mpl):   27
fps  (GR):   89
  speedup:    3.3
```

**Comment by jheinen** [comment]
Well, with Julia I get up to 500 fps for GR and 14 fps for MPL on macOS 10.15 (Catalina). I start Julia with the '`-i` option to be able to manually call and then compare `gr()` and `mpl()`. I currently have no other test environment, can make further tests on Monday ...

With Python, the speedup is similar to what you observed (using the following script):

```python
from pylab import plot, draw, pause
from numpy import arange, sin, pi
from time import time, sleep

x = arange(0, 2 * pi, 0.01)

def mpl():
    tstart = time()
    line, = plot(x, sin(x))
    for i in arange(1, 200):
        line.set_ydata(sin(x + i / 10.0))
        draw()
        pause(0.0001)

    fps_mpl = int(200 / (time() - tstart))
    print('fps (mpl): %4d' % fps_mpl)
    return fps_mpl

import gr.pygr as GR

def gr():
    tstart = time()
    for i in arange(1, 200):
        GR.plot(x, sin(x + i / 10.0))
        sleep(0.0001)

    fps_gr = int(200 / (time() - tstart))
    print('fps  (GR): %4d' % fps_gr)
    return fps_gr

fps_mpl = mpl()
fps_gr = gr()

print('  speedup: %6.1f' % (float(fps_gr) / fps_mpl))
```

**Comment by FlorianRhiem** [comment]
As part of a series of fixes to the examples, including porting many of them from Python 2, I have also updated this example as part of today's release 1.15.0. While I was able to receive a performance increase with GR, it didn't get close to the old speedup.

As both GR and matplotlib change and improve, I expect the performance to continue changing and have removed the out of date numbers.
