### ISSUE TITLE
Pick mode crosshair is not positioned correctly

### ISSUE THREAD

**Issue by EmDash00** [sciapp/python-gr#9]
I was playing around a bit with qtgrdemo example.The pick button which sets the pick mode of the interactive plot (plot 1) picks point coordinates properly but doesn't draw the crosshair on the right location. I've attached a photo of the behavior. Ignore the absent 2nd widget. I removed it on accident while removing the linear plot.

![Screenshot from 2019-08-09 14-08-38](https://user-images.githubusercontent.com/22357488/62799588-38699f00-baaf-11e9-83a5-b549766d96cd.png)

**Comment by FlorianRhiem** [comment]
This was fixed in 7f4f0c68ce28eb6ba4788d06b4ed591bc04b6f19 and released in v1.11.2.
